### ISSUE TITLE
Specify collections.properties and permissions.properties on top level

### ISSUE THREAD

**Issue by peetkes** [marklogic/ml-javaclient-util#173]
It would be nice/convenient to be able to specify the collections.properties and permissions.properties on the top-level of a folder structure and be able to override this in deeper levels.

This to prevent the fact that you have to specify the properties on each level of a deeply nested folder structure

**Comment by rjrudin** [comment]
In terms of implementing (the design for a user is simple - it should "just work", possibly with a boolean to disable the behavior if desired) - this should involve a change to `DefaultDocumentFileReader`, which is the class that descends through a file tree. DDFR would need the concept of "DocumentFileProcessor instances that should apply to the current directory and to child directories". 

Looking at DDFR, I remember wanting to get rid of the fact that it has instances of the collections and permissions processors. Those are only there so that a `TokenReplacer` can be given to each of them. That should be abstracted away - i.e. an interface could be added such as `NeedsTokenReplacer` and then `GenericFileLoader` would hand the `TokenReplacer` to DDFR, who would check to see which of its document file processors need a token replacer. 

Then, I think `PropertiesDrivenDocumentFileProcessor` could support the notion of "Apply me to the directory where my properties file is found, and also all child directories".

**Comment by peetkes** [comment]
You are right Rob, I would expect it to work like you described. A properties file on a deeper level should take precedence over a higher level file. In the ideal world it should also be that the generic high level works for all lower level unspecified files.
So if on the top level I would specify *=collectionA and at level 3 I specify fileName=collectionB, then very file in the toplevel down to the lowest level should get collectionB except for all files with name 'fileName' on level 3 and deeper would get collectionB.

**Comment by peetkes** [comment]
This is basically the same as #120 and I guess this has not been implemented?

**Comment by rjrudin** [comment]
Resolved via #186, will be documented in this project and ml-gradle docs will refer to it.
